import { Router } from "express";
import { getApiInformation } from "../controllers/api.controller.js";
import blockPlannerRouter from "./block-planner.routes.js";
import databaseRouter from "./database.routes.js";
import dashboardRouter from "./dashboard.routes.js";
import riskRouter from "./risk.routes.js";
import pythonRouter from "./python.routes.js";
import redisRouter from "./redis.routes.js";
import priorityRouter from "./priority.routes.js";
import minioRouter from "./minio.routes.js";
import networkRouter from "./network.routes.js";
import tasksRouter from "./tasks.routes.js";
import assetsRouter from "./assets.routes.js";
import blocksRouter from "./blocks.routes.js";
import blockWindowsRouter from "./block-windows.routes.js";
import sectionsRouter from "./sections.routes.js";
import conflictsRouter from "./conflicts.routes.js";
import workspaceRouter from "./workspace.routes.js";
import planVersionsRouter from "./plan-versions.routes.js";
export const apiRouter = Router();

apiRouter.get("/", getApiInformation);
apiRouter.use(databaseRouter);
apiRouter.use(dashboardRouter);
apiRouter.use(riskRouter);
apiRouter.use(blockPlannerRouter);
apiRouter.use(pythonRouter);
apiRouter.use(redisRouter);
apiRouter.use(minioRouter);
apiRouter.use(networkRouter);
apiRouter.use(workspaceRouter);
apiRouter.use(planVersionsRouter);
apiRouter.use("/priority", priorityRouter);
apiRouter.use("/tasks", tasksRouter);
apiRouter.use("/assets", assetsRouter);
apiRouter.use("/blocks", blocksRouter);
apiRouter.use("/block-windows", blockWindowsRouter);
apiRouter.use("/sections", sectionsRouter);
apiRouter.use("/conflicts", conflictsRouter);
